# Generated by Django 2.1.1 on 2019-03-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, default='profile/no-picture.jpg', max_length=255, null=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
