# Generated by Django 2.2.3 on 2019-07-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='full name'),
        ),
    ]
