# Generated by Django 2.1.1 on 2019-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190308_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/none/no-img.jpg', max_length=255, null=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
