# Generated by Django 2.2.3 on 2019-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190726_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/none/no-image-profile.png', max_length=255, null=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
