# Generated by Django 3.0.5 on 2020-04-13 20:53
import autoslug.fields
import django.db.models.deletion
import django_extensions.db.fields
import imagekit.models.fields
from django.db import migrations
from django.db import models

import apps.assets.models
import apps.assets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("brushes", "Brush"),
                            ("patterns", "Pattern"),
                            ("gradients", "Gradient"),
                            ("palettes", "Palette"),
                            ("plug-ins", "Plug-in"),
                        ],
                        max_length=9,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(max_length=3000)),
                ("source", models.URLField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=apps.assets.models.get_file_path,
                        validators=[
                            apps.assets.validators.FileValidator(
                                max_size=10485760
                            )
                        ],
                    ),
                ),
                ("filesize", models.IntegerField(default=0, editable=False)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        default="images/no-img.png",
                        max_length=255,
                        null=True,
                        upload_to=apps.assets.models.get_image_path,
                        validators=[
                            apps.assets.validators.FileValidator(
                                max_size=10485760
                            )
                        ],
                    ),
                ),
                (
                    "num_likes",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "num_downloads",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "num_views",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked",
                        to="assets.Asset",
                    ),
                ),
            ],
        ),
    ]
