# Generated by Django 3.0.5 on 2020-04-13 22:17
import django.contrib.auth.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text="Required. 15 characters or fewer. Letters,  numbers and @/./+/-/_ characters",
                max_length=15,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                ],
                verbose_name="username",
            ),
        )
    ]
