# Generated by Django 2.1.1 on 2019-04-03 00:11

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('brush', 'Brush'), ('pattern', 'Pattern'), ('gradient', 'Gradient'), ('plugin', 'Plugin')], max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to=assets.models.get_file_path)),
                ('filesize', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='images/none/no-img.jpg', null=True, upload_to=assets.models.get_image_path)),
                ('num_likes', models.PositiveIntegerField(default=0)),
                ('num_downloads', models.PositiveIntegerField(default=0)),
                ('num_shares', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
