# Generated by Django 2.1.1 on 2019-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, default='images/none/no-img.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/none/no-thumb.jpg', null=True, upload_to='thumbnails/'),
        ),
    ]
