# Generated by Django 2.2 on 2019-04-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('folder', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('brushes', 'Brush'), ('patterns', 'Pattern'), ('gradients', 'Gradient'), ('plug-ins', 'Plug-in')], max_length=9),
        ),
    ]
