# Generated by Django 2.1.1 on 2019-02-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190214_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='num_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='num_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='num_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
