# Generated by Django 2.1.1 on 2019-02-27 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190214_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
            ],
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
            ],
            bases=('assets.asset',),
        ),
    ]
