# Generated by Django 2.2 on 2019-04-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190412_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='type2',
        ),
    ]
