# Generated by Django 2.1.1 on 2019-03-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_gradient_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
