# Generated by Django 2.1.1 on 2019-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
    ]
