# Generated by Django 2.2 on 2019-04-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='type2',
        ),
    ]
