# Generated by Django 2.1.1 on 2019-03-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('brush', 'Brush'), ('pattern', 'Pattern'), ('gradient', 'Gradient'), ('plugin', 'Plugin')], default='brush', max_length=9),
        ),
    ]
