# Generated by Django 2.2 on 2019-04-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20190418_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('brushes', 'Brush'), ('patterns', 'Pattern'), ('gradients', 'Gradient'), ('plug-ins', 'Plug-in')], default='brush', max_length=9),
            preserve_default=False,
        ),
    ]
