# Generated by Django 2.2 on 2019-05-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20190418_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
