# Generated by Django 2.2.3 on 2019-07-09 20:52

import autoslug.fields
from django.db import migrations, models

from assets.models import Asset

def migrate_data_forward(apps, schema_editor):
    for instance in Asset.objects.all():
        print ("Generating slug for %s"%instance)
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
