# Generated by Django 2.2.3 on 2019-08-06 13:55

import assets.models
import assets.validators
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20190806_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/none/no-img.jpg', null=True, upload_to=assets.models.get_image_path, validators=[assets.validators.FileValidator(max_size=10485760)]),
        ),
    ]
