# Generated by Django 2.2.3 on 2019-08-06 18:53

import assets.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20190806_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assets.validators.PathAndRename('assets'), validators=[assets.validators.FileValidator(max_size=10485760)]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='filesize',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/no-img.png', null=True, upload_to=assets.validators.PathAndRename('images'), validators=[assets.validators.FileValidator(max_size=10485760)]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='num_downloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='num_likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='num_shares',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
